config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  
  get 'signup'  => 'users#new'
  #get 'create_user'  => 'users#new'
  get 'create_circle'  => 'circles#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get  'schedules/show'
  get  'schedules/new'
  post 'schedules/new'
  post 'schedules/create'
  get 'schedules/edit'



  resources :users
  resources :circles
  resources :circle_events

end

app/models/circle.rb
class Circle < ActiveRecord::Base
end

app/models/circle_event.rb
class CircleEvent < ActiveRecord::Base
    validates :circle_id,    presence: true, length:{maximum:11}
    validates :event_date,   presence: true
    validates :event_detail, presence: true, length:{maximum:500}
    validates :user_id,      presence: true, length:{maximum:11}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  # 名前のチェック
  validates :name,  presence: true, length: { maximum: 50 }
  
  # メアドのフォーマット（正規表現
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  # メアドのチェック
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # パスワードのハッシュ化
  has_secure_password
  
  # パスワードのチェック
  validates :password, presence: true, length: { minimum: 6 }
  
  
  # 与えられた文字列のハッシュ値を返す 
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションで使用するユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #protect_from_forgery with: :null_session
  include SessionsHelper
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  def show
    @circle = Circle.find(params[:id])
    if @circle.official_flg
      @official = '公式部活動'
    else
      @official = '非公式部活動'
    end
  end
  
  def new
    @circle = Circle.new
  end
  
  def create
    @circle = Circle.new(circle_params)
    if @circle.save
      redirect_to @circle
    else
      render 'new'
    end
  end
  
  private

  def circle_params
    params.require(:circle).permit(:name, :detail, :official_flg)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def create
    @circle_event = CircleEvent.new(user_params)
    if @circle_event.save
      render 'show'
    else
      render 'new'
    end
  end

  def edit
  end  
  
  def new
    @circle = Circle.new
    @circle_event = CircleEvent.new
  end  
  
  def show
    @circle_event = CircleEvent.new
  end
  
  private

    def user_params
      params.require(:circle_event).permit(:circle_id, :event_date, :event_detail,:user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in user
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    # debugger
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      # ↓これと同じredirect_to user_url(@user)
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation,:detail)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーを永続的セッションに記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # 現在ログインしているユーザーを返す (ユーザーがログイン中の場合のみ)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/circles/new.html.erb
<h1>部活動登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@circle) do |f| %>
      <%= f.label :'name', '部活名' %>
      <%= f.text_field :name %>

      <%= f.label :'detail', '活動内容' %>
      <%= f.text_area :detail %>
      
      <%= f.label :'official_flg', 'NB公式' %><br />
      <%= f.select :official_flg, {"公式" => 1, "非公式" => "0"} %>

      <%= f.submit "Create New Circle", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/circles/show.html.erb
<h1><%= @official %></h1>
<h1><%= @circle.name %></h1>
<h3><%= @circle.detail %></h3>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    ⒸNijibox
  </small>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="col-sm-3 col-md-2 navbar-inner">
        <%= link_to image_tag("top_singeki2.png", alt:"社内部活広報"), root_path %>
      </div>
      <div id="navbar" class="col-sm-9 col-md-10 navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Top", root_path %></li>
          <li><%= link_to "Help", '#' %></li>
          <li><a href="#">Settings</a></li>
        <% if logged_in? %>
          <li><%= link_to "マイページ", current_user %></li>
          <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<ul class="nav nav-sidebar">
  <li class="active"><%= link_to "Top", root_path %></li>
  <li><%= link_to "スケジュール登録", "/schedules/new" %></li>
</ul>
<ul class="nav nav-sidebar">
  <li><a href="">Nav item again</a></li>
  <li><a href="">One more nav</a></li>
  <li><a href="">Another nav item</a></li>
  <li><a href="">More navigation</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>社内部活広報(仮)！！</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

<%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
<%= render 'layouts/sidebar' %>
        </div>
        <div class="col-sm-9 col-md-10 container main">
//ここに各ページのものが表示される
          <%= yield %>
<%= debug(params) %>
        </div>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/schedules/edit.html.erb
<h1>Schedules#edit</h1>
<button>スケジュール編集</button>

app/views/schedules/new.html.erb
<h1>Schedules#new</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@circle_event,:url =>{:action =>'create'}) do |f| %>
      <%= f.label :circle_id, "circle_id" %>
      <%= f.collection_select :circle_id, Circle.all, :id, :name %>

      <%= f.label :event_date, "event_date" %>
<div class="controls">
  <%= f.text_field :event_date, 
                   data: { :date_format => 'YYYY/MM/DD hh:mm' }, 
                   :class => 'form-control datetimepicker', 
                   placeholder: 'YYYY/MM/DD hh:mm:ss'
    %>
</div>
      <%= f.label :event_detail, "event_detail" %>
      <%= f.text_field :event_detail %>
      <!--いったん固定値-->
    <input type="hidden" name="circle_event[user_id]" value="1">
    
      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/schedules/show.html.erb
<h1>Schedules#show</h1>
<div id="calendar"></div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :detail %>
      <%= f.text_field :detail, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>